title: Portfólio de Dados
logo: /assets/img/icon.png
email: andreluizlcons@gmail.com
description: Projetos de machine learning
show_downloads: false
# google_analytics: G-ZLK2GHB055
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/datalopes1


# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
